blank_issues_enabled: false
contact_links:
  - name: 讨论区
    url: https://github.com/Mereithhh/van-blog/discussions/new
    about: 前往讨论区与大家交流

  - name: 官方 QQ 群
    url: https://jq.qq.com/?_wv=1027&k=5NRyK2Sw
    about: '加入 VanBlog 用户交流群: 743037540'

  # - name: Telegram
  #   url: https://t.me/walinejs
  #   about: 'Official Telegram Group'
